defaultName: myDefaultName

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

swagger:
  resourcePackage: com.example.demo

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: rootx
  url: jdbc:mysql://127.0.0.1:3306/example
  properties:
    charSet: UTF-8